### ISSUE TITLE
Path to litle_SDK_config.ini file (and its name too) file need to be configurable

### ISSUE THREAD

**Issue by eproand** [LitleCo/litle-sdk-for-php#28]
If I am missing something, please point that out. My understanding that I need to configure litle_SDK_config.ini file in order to run/use the SDK (by the way it's really not clear from the limited docs how and where to configure SDK, documentation needs to be improved). It is unfortunate that there is no way to point the SDK to use a provided config file from a non-vendor/custom directory (e.g. /configs/vantiv-config.ini). It does not make too much sense to have this file modified inside the vendors folder (/vendors/litle/...) because of composer (should be able to recreate/reinstall litle SDK without overriding my config file).

I think this issue is critical and needs to be address. Thank you.

**Comment by amitvig22** [comment]
To answer your first question, the install instructions do suggest that you run setup.php. Doing so will configure the litle_SDK_config.ini

And you are correct to point out that the config file needs to stay in the sdk dir of the PHP sdk, if you reinstall the SDK you can reuse the old file. You are not required to run the setup again. Additionally the SDKs are open source if you would like to modify the sdk to read config files from another location you can do so.
